trigger:
  branches:
    include:
      - main

variables:
- name: dockerfile
  value: '.'
  #imageName: 'testflaskacr/flask-app:$(Build.BuildId)'

# jobs:
# - job: BuildAndPushDockerImage
#   displayName: 'Build and Push Docker Image'
pool:
  vmImage: 'ubuntu-latest'

steps:  
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: build
    containerRegistry: 'Test-sc-docker'
    repository: 'testflaskacr/flask-app'
    dockerfile: '**/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'

- task: Docker@2
  displayName: 'Push Docker image to ACR'
  inputs:
    command: push
    containerRegistry: 'Test-sc-docker'
    repository: 'testflaskacr/flask-app'
    dockerfile: '**/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'







  #- task: Docker@2
  # displayName: 'Push Docker Image'
  # inputs:
  #    command: 'push'
  #    repository: ${{ variables.repository }}
  #    containerRegistry:  ${{ variables.containerRegistry }}
  #   imageName: 'testflaskacr/flask-app:$(Build.BuildId)'

  #      displayName: 'Build and push an image to container registry'
  #       inputs:
  #         command: 'buildAndPush'
  #         repository: ${{ variables.repository }}
  #         dockerfile: ${{ variables.dockerfile }}
  #         containerRegistry: ${{ variables.containerRegistry }}
  #   tags: $(Build.BuildId)
